/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Tender } from '../types';

export const initialTenders: Tender[] = [
  // ME-399 - Lab Group
  {
    id: 't-1',
    slNo: 1,
    department: 'Lab',
    equipmentName: 'Cal Lab-10',
    tenderNo: 'ME-399',
    openedDate: '16.07.2025',
    endDate: '15.01.2026',
    statusText: 'Post-TEC meeting was scheduled on 17.02.2025. Minutes under signing. Re-tender recommended (single bid condition).',
    manager: 'Girish',
    preBidMeeting: 'Completed',
    tscMeeting: 'Completed',
    technicalOpening: 'Opened (16.07.2025)',
    bidderName: 'Single Bidder',
    noOfBidders: 1,
    tecMeeting: 'Completed (17.02.2025)',
    postTecMeeting: 'Minutes under signing',
    tec2Meeting: 'N/A',
    demoMeeting: 'N/A',
    postDemoMeeting: 'N/A',
    financialOpening: 'Pending',
    priceJustificationMeeting: 'Pending',
    awardOfContract: 'Re-tender recommended',
    agreement: 'N/A'
  },
  {
    id: 't-2',
    slNo: 2,
    department: 'Lab',
    equipmentName: 'Skill Lab-10',
    tenderNo: 'ME-399',
    openedDate: '16.07.2025',
    endDate: '15.01.2026',
    statusText: 'Post-TEC meeting was scheduled on 17.02.2025. Minutes under signing. Re-tender recommended (single bid condition).',
    manager: 'Girish',
    preBidMeeting: 'Completed',
    tscMeeting: 'Completed',
    technicalOpening: 'Opened (16.07.2025)',
    bidderName: 'Single Bidder',
    noOfBidders: 1,
    tecMeeting: 'Completed (17.02.2025)',
    postTecMeeting: 'Minutes under signing',
    tec2Meeting: 'N/A',
    demoMeeting: 'N/A',
    postDemoMeeting: 'N/A',
    financialOpening: 'Pending',
    priceJustificationMeeting: 'Pending',
    awardOfContract: 'Re-tender recommended',
    agreement: 'N/A'
  },
  {
    id: 't-3',
    slNo: 3,
    department: 'Lab',
    equipmentName: 'Clinical Pharmacy lab-10',
    tenderNo: 'ME-399',
    openedDate: '16.07.2025',
    endDate: '15.01.2026',
    statusText: 'Post-TEC meeting was scheduled on 17.02.2025. Minutes under signing. Re-tender recommended (single bid condition).',
    manager: 'Girish',
    preBidMeeting: 'Completed',
    tscMeeting: 'Completed',
    technicalOpening: 'Opened (16.07.2025)',
    bidderName: 'Single Bidder',
    noOfBidders: 1,
    tecMeeting: 'Completed (17.02.2025)',
    postTecMeeting: 'Minutes under signing',
    tec2Meeting: 'N/A',
    demoMeeting: 'N/A',
    postDemoMeeting: 'N/A',
    financialOpening: 'Pending',
    priceJustificationMeeting: 'Pending',
    awardOfContract: 'Re-tender recommended',
    agreement: 'N/A'
  },
  {
    id: 't-4',
    slNo: 4,
    department: 'Lab',
    equipmentName: 'P.G Research Lab',
    tenderNo: 'ME-399',
    openedDate: '16.07.2025',
    endDate: '15.01.2026',
    statusText: 'Post-TEC meeting was scheduled on 17.02.2025. Minutes under signing. Re-tender recommended (single bid condition).',
    manager: 'Girish',
    preBidMeeting: 'Completed',
    tscMeeting: 'Completed',
    technicalOpening: 'Opened (16.07.2025)',
    bidderName: 'Single Bidder',
    noOfBidders: 1,
    tecMeeting: 'Completed (17.02.2025)',
    postTecMeeting: 'Minutes under signing',
    tec2Meeting: 'N/A',
    demoMeeting: 'N/A',
    postDemoMeeting: 'N/A',
    financialOpening: 'Pending',
    priceJustificationMeeting: 'Pending',
    awardOfContract: 'Re-tender recommended',
    agreement: 'N/A'
  },

  // ME-421 - Physiology Laboratory NMC Guideline (5-20)
  ...[
    { id: 't-5', slNo: 5, name: 'Electrical E8 student kymograph' },
    { id: 't-6', slNo: 6, name: 'Perimeter Pristely Smith model' },
    { id: 't-7', slNo: 7, name: "Mosso's Ergograph" },
    { id: 't-8', slNo: 8, name: 'Perimeter Lister type' },
    { id: 't-9', slNo: 9, name: 'Digital Perimeter' },
    { id: 't-10', slNo: 10, name: 'Bicycle Ergometer' },
    { id: 't-11', slNo: 11, name: 'Polygraph' },
    { id: 't-12', slNo: 12, name: 'Physiograph' },
    { id: 't-13', slNo: 13, name: 'Pentahead Microscope' },
    { id: 't-14', slNo: 14, name: 'Wright peak Flowmeter' },
    { id: 't-15', slNo: 15, name: 'Handgrip dynamometer' },
    { id: 't-16', slNo: 16, name: 'Demonstration stethocope' },
    { id: 't-17', slNo: 17, name: 'Tilt table' },
    { id: 't-18', slNo: 18, name: 'Dales organ Bath' },
    { id: 't-19', slNo: 19, name: 'harvard step (Wooden box) 20" Males, 16" Females' },
    { id: 't-20', slNo: 20, name: 'Spirometer Digital' }
  ].map(item => ({
    id: item.id,
    slNo: item.slNo,
    department: 'Physiology Laboratory NMC Guideline',
    equipmentName: item.name,
    tenderNo: 'ME-421',
    openedDate: '16.07.2025',
    endDate: '15.01.2026',
    statusText: 'Post demo tec meeting completed. Financial Committee meeting held on 22/01/2026. Price Justification meeting held on 25.03.2026. Minutes in Signed.',
    manager: 'Girish',
    preBidMeeting: 'Completed',
    tscMeeting: 'Completed',
    technicalOpening: 'Opened',
    bidderName: 'Cleared Bidders',
    noOfBidders: 3,
    tecMeeting: 'Completed',
    postTecMeeting: 'Post-demo TEC completed',
    tec2Meeting: 'N/A',
    demoMeeting: 'Completed',
    postDemoMeeting: 'Completed',
    financialOpening: 'Opened (22/01/2026)',
    priceJustificationMeeting: 'Completed (25.03.2026)',
    awardOfContract: 'Approved (Minutes Signed)',
    agreement: 'Drafting'
  })),

  // ME-428 - Cardiology (21-22)
  {
    id: 't-21',
    slNo: 21,
    department: 'Cardiology',
    equipmentName: 'High End Echocardiography-10',
    tenderNo: 'ME-428',
    openedDate: '11.08.2025',
    endDate: '10.02.2026',
    statusText: 'Recommended for re-tender of the equipment due to single bid / zero bid condition.',
    manager: 'Girish',
    preBidMeeting: 'Completed',
    tscMeeting: 'Completed',
    technicalOpening: 'Opened',
    bidderName: 'Siemens / Lapsed',
    noOfBidders: 1,
    tecMeeting: 'Evaluated',
    postTecMeeting: 'N/A',
    tec2Meeting: 'N/A',
    demoMeeting: 'N/A',
    postDemoMeeting: 'N/A',
    financialOpening: 'Cancelled',
    priceJustificationMeeting: 'N/A',
    awardOfContract: 'Re-tender recommended (Zero/single bid)',
    agreement: 'N/A'
  },
  {
    id: 't-22',
    slNo: 22,
    department: 'Cardiology',
    equipmentName: 'Echocardiogram (ECHO) Machine-36',
    tenderNo: 'ME-428',
    openedDate: '11.08.2025',
    endDate: '10.02.2026',
    statusText: 'Recommended for re-tender of the equipment due to single bid / zero bid condition.',
    manager: 'Girish',
    preBidMeeting: 'Completed',
    tscMeeting: 'Completed',
    technicalOpening: 'Opened',
    bidderName: 'Siemens / Lapsed',
    noOfBidders: 1,
    tecMeeting: 'Evaluated',
    postTecMeeting: 'N/A',
    tec2Meeting: 'N/A',
    demoMeeting: 'N/A',
    postDemoMeeting: 'N/A',
    financialOpening: 'Cancelled',
    priceJustificationMeeting: 'N/A',
    awardOfContract: 'Re-tender recommended (Zero/single bid)',
    agreement: 'N/A'
  },

  // ME-429 - Transport & MVI (23-24)
  {
    id: 't-23',
    slNo: 23,
    department: 'Transport & MVI Deptt.',
    equipmentName: '(i) Basic Mortuary vehicle (Air Conditioner)-12',
    tenderNo: 'ME-429',
    openedDate: '25.07.2025',
    statusText: 'Board approval pending.',
    manager: 'Girish',
    preBidMeeting: 'Completed',
    tscMeeting: 'Completed',
    technicalOpening: 'Opened',
    bidderName: 'Board Reviewers',
    noOfBidders: 2,
    tecMeeting: 'Completed',
    postTecMeeting: 'Pending Approval',
    tec2Meeting: 'N/A',
    demoMeeting: 'N/A',
    postDemoMeeting: 'N/A',
    financialOpening: 'Awaiting Board Approval',
    priceJustificationMeeting: 'Pending',
    awardOfContract: 'Awaiting Approval',
    agreement: 'Drafting'
  },
  {
    id: 't-24',
    slNo: 24,
    department: 'Transport & MVI Deptt.',
    equipmentName: '(ii) Mortuary Vehicle With Freezer-02',
    tenderNo: 'ME-429',
    openedDate: '25.07.2025',
    statusText: 'Board approval pending.',
    manager: 'Girish',
    preBidMeeting: 'Completed',
    tscMeeting: 'Completed',
    technicalOpening: 'Opened',
    bidderName: 'Board Reviewers',
    noOfBidders: 2,
    tecMeeting: 'Completed',
    postTecMeeting: 'Pending Approval',
    tec2Meeting: 'N/A',
    demoMeeting: 'N/A',
    postDemoMeeting: 'N/A',
    financialOpening: 'Awaiting Board Approval',
    priceJustificationMeeting: 'Pending',
    awardOfContract: 'Awaiting Approval',
    agreement: 'Drafting'
  },

  // ME-405 - ICU, Chest, PICU Group (25-27)
  {
    id: 't-25',
    slNo: 25,
    department: 'ICU/ Anaesthesia',
    equipmentName: 'Transport Ventilator-200',
    tenderNo: 'ME-405',
    openedDate: '17.10.2025',
    endDate: '16.04.2026',
    statusText: 'Demo meetings on 20.04.2026, 21.04.2026 and 22.04.2026 completed. Post Demonstration meeting schedule on 12.05.2026. File under approval.',
    manager: 'Girish',
    preBidMeeting: 'Completed',
    tscMeeting: 'Completed',
    technicalOpening: 'Opened',
    bidderName: 'Evaluated Bidders',
    noOfBidders: 4,
    tecMeeting: 'Completed',
    postTecMeeting: 'Completed',
    tec2Meeting: 'N/A',
    demoMeeting: 'Completed (22.04.2026)',
    postDemoMeeting: 'Completed (12.05.2026)',
    financialOpening: 'Pending',
    priceJustificationMeeting: 'Pending',
    awardOfContract: 'File Under Approval',
    agreement: 'Draft'
  },
  {
    id: 't-26',
    slNo: 26,
    department: 'TB & Chest',
    equipmentName: 'BIPAP Machine-100',
    tenderNo: 'ME-405',
    openedDate: '17.10.2025',
    endDate: '16.04.2026',
    statusText: 'Demo meetings on 20.04.2026, 21.04.2026 and 22.04.2026 completed. Post Demonstration meeting schedule on 12.05.2026. File under approval.',
    manager: 'Girish',
    preBidMeeting: 'Completed',
    tscMeeting: 'Completed',
    technicalOpening: 'Opened',
    bidderName: 'Evaluated Bidders',
    noOfBidders: 4,
    tecMeeting: 'Completed',
    postTecMeeting: 'Completed',
    tec2Meeting: 'N/A',
    demoMeeting: 'Completed (22.04.2026)',
    postDemoMeeting: 'Completed (12.05.2026)',
    financialOpening: 'Pending',
    priceJustificationMeeting: 'Pending',
    awardOfContract: 'File Under Approval',
    agreement: 'Draft'
  },
  {
    id: 't-27',
    slNo: 27,
    department: 'PICU/NICU',
    equipmentName: 'Radiant Warmer-500',
    tenderNo: 'ME-405',
    openedDate: '17.10.2025',
    endDate: '16.04.2026',
    statusText: 'Demo meetings on 20.04.2026, 21.04.2026 and 22.04.2026 completed. Post Demonstration meeting schedule on 12.05.2026. File under approval.',
    manager: 'Girish',
    preBidMeeting: 'Completed',
    tscMeeting: 'Completed',
    technicalOpening: 'Opened',
    bidderName: 'Evaluated Bidders',
    noOfBidders: 4,
    tecMeeting: 'Completed',
    postTecMeeting: 'Completed',
    tec2Meeting: 'N/A',
    demoMeeting: 'Completed (22.04.2026)',
    postDemoMeeting: 'Completed (12.05.2026)',
    financialOpening: 'Pending',
    priceJustificationMeeting: 'Pending',
    awardOfContract: 'File Under Approval',
    agreement: 'Draft'
  },

  // ME-435 - Pediatrics & Cardiology Defibrillator (28-29)
  {
    id: 't-28',
    slNo: 28,
    department: 'Anaethesia/Pediatrics',
    equipmentName: 'Pulse Oxymeter (Desktop Type)',
    tenderNo: 'ME-435',
    openedDate: '17.10.2025',
    endDate: '16.04.2026',
    statusText: '“Heidelco Medicore Private Limited inadvertently presented an incorrect model; re-demonstration requested via email. Re-demo Schedule on 06-05-2026. File under approval.',
    manager: 'Girish',
    preBidMeeting: 'Completed',
    tscMeeting: 'Completed',
    technicalOpening: 'Opened',
    bidderName: 'Heidelco Medicore Private Ltd',
    noOfBidders: 2,
    tecMeeting: 'Incomplete Modell',
    postTecMeeting: 'Reviewing',
    tec2Meeting: 'N/A',
    demoMeeting: 'Re-demo Schedule on 06-05-2026',
    postDemoMeeting: 'Pending',
    financialOpening: 'Pending',
    priceJustificationMeeting: 'Pending',
    awardOfContract: 'Awaiting Correct Demo',
    agreement: 'N/A'
  },
  {
    id: 't-29',
    slNo: 29,
    department: 'Cardiology',
    equipmentName: 'Defibrillator',
    tenderNo: 'ME-435',
    openedDate: '17.10.2025',
    endDate: '16.04.2026',
    statusText: '“Heidelco Medicore Private Limited inadvertently presented an incorrect model; re-demonstration requested via email. Re-demo Schedule on 06-05-2026. File under approval.',
    manager: 'Girish',
    preBidMeeting: 'Completed',
    tscMeeting: 'Completed',
    technicalOpening: 'Opened',
    bidderName: 'Heidelco Medicore Private Ltd',
    noOfBidders: 2,
    tecMeeting: 'Incomplete Model',
    postTecMeeting: 'Reviewing',
    tec2Meeting: 'N/A',
    demoMeeting: 'Re-demo Schedule on 06-05-2026',
    postDemoMeeting: 'Pending',
    financialOpening: 'Pending',
    priceJustificationMeeting: 'Pending',
    awardOfContract: 'Awaiting Correct Demo',
    agreement: 'N/A'
  },

  // ME-425 - Radiology MRI PPP Bettiah (30)
  {
    id: 't-30',
    slNo: 30,
    department: 'Radiology',
    equipmentName: 'MRI Machine under Public Private Partnership (PPP) Mode for Government Medical College & Hospital, Bettiah of Bihar',
    tenderNo: 'ME-425',
    openedDate: '12.11.2025',
    endDate: '11.05.2026',
    statusText: 'Post Tec meeting scheduled on Date-30.01.2026 at 11:00 am. Re-tender recommended (single bid condition).',
    manager: 'Girish',
    preBidMeeting: 'Completed',
    tscMeeting: 'Completed',
    technicalOpening: 'Opened',
    bidderName: 'Single Bidder',
    noOfBidders: 1,
    tecMeeting: 'Completed (30.01.2026)',
    postTecMeeting: 'Re-tender recommended (Single bid)',
    tec2Meeting: 'N/A',
    demoMeeting: 'N/A',
    postDemoMeeting: 'N/A',
    financialOpening: 'Cancelled',
    priceJustificationMeeting: 'N/A',
    awardOfContract: 'Re-tender recommended',
    agreement: 'N/A'
  },

  // ME-437 - Gynaecology & Pediatrics (31-32)
  {
    id: 't-31',
    slNo: 31,
    department: 'Gyanecology',
    equipmentName: 'LDR/Delivery Bed',
    tenderNo: 'ME-437',
    openedDate: '14.11.2025',
    endDate: '13.05.2026',
    statusText: 'Tec meeting held on 20.03.2026. Minutes under signing. Demo meeting schedule on 05.05.2026. File under approval.',
    manager: 'Girish',
    preBidMeeting: 'Completed',
    tscMeeting: 'Completed',
    technicalOpening: 'Opened',
    bidderName: 'Shortlisted Bidders',
    noOfBidders: 3,
    tecMeeting: 'Completed (20.03.2026)',
    postTecMeeting: 'Minutes under signing',
    tec2Meeting: 'N/A',
    demoMeeting: 'Scheduled (05.05.2026)',
    postDemoMeeting: 'Completed',
    financialOpening: 'Pending',
    priceJustificationMeeting: 'Pending',
    awardOfContract: 'File Under Approval',
    agreement: 'Draft'
  },
  {
    id: 't-32',
    slNo: 32,
    department: 'Paeditrics',
    equipmentName: 'CPAP (Continuous Positive Airway pressure)',
    tenderNo: 'ME-437',
    openedDate: '14.11.2025',
    endDate: '13.05.2026',
    statusText: 'Tec meeting held on 20.03.2026. Minutes under signing. Demo meeting schedule on 05.05.2026. File under approval.',
    manager: 'Girish',
    preBidMeeting: 'Completed',
    tscMeeting: 'Completed',
    technicalOpening: 'Opened',
    bidderName: 'Shortlisted Bidders',
    noOfBidders: 3,
    tecMeeting: 'Completed (20.03.2026)',
    postTecMeeting: 'Minutes under signing',
    tec2Meeting: 'N/A',
    demoMeeting: 'Scheduled (05.05.2026)',
    postDemoMeeting: 'Completed',
    financialOpening: 'Pending',
    priceJustificationMeeting: 'Pending',
    awardOfContract: 'File Under Approval',
    agreement: 'Draft'
  },

  // ME-432 - TB & Chest, Endoscopy (33-34)
  {
    id: 't-33',
    slNo: 33,
    department: 'TB & Chest',
    equipmentName: 'Video Bronchoscope',
    tenderNo: 'ME-432',
    openedDate: '19.11.2025',
    endDate: '18.05.2026',
    statusText: 'Demos meeting on 04.05.2026 & 05.05.2026; 04.05.2026 completed, "Post Demonstration meeting Schedule on 12.05.2026. File Under approval.',
    manager: 'Girish',
    preBidMeeting: 'Completed',
    tscMeeting: 'Completed',
    technicalOpening: 'Opened',
    bidderName: 'Shortlisted Bidders',
    noOfBidders: 3,
    tecMeeting: 'Completed',
    postTecMeeting: 'Completed',
    tec2Meeting: 'N/A',
    demoMeeting: 'Completed (04.05.2026)',
    postDemoMeeting: 'Scheduled (12.05.2026)',
    financialOpening: 'Pending',
    priceJustificationMeeting: 'Pending',
    awardOfContract: 'File Under approval',
    agreement: 'Draft'
  },
  {
    id: 't-34',
    slNo: 34,
    department: 'Endoscopy',
    equipmentName: 'Endoscopy System Upper GI Endoscopy & Lower GI Endoscope',
    tenderNo: 'ME-432',
    openedDate: '19.11.2025',
    endDate: '18.05.2026',
    statusText: 'Demos meeting on 04.05.2026 & 05.05.2026; 04.05.2026 completed, "Post Demonstration meeting Schedule on 12.05.2026. File Under approval.',
    manager: 'Girish',
    preBidMeeting: 'Completed',
    tscMeeting: 'Completed',
    technicalOpening: 'Opened',
    bidderName: 'Shortlisted Bidders',
    noOfBidders: 3,
    tecMeeting: 'Completed',
    postTecMeeting: 'Completed',
    tec2Meeting: 'N/A',
    demoMeeting: 'Completed (04.05.2026)',
    postDemoMeeting: 'Scheduled (12.05.2026)',
    financialOpening: 'Pending',
    priceJustificationMeeting: 'Pending',
    awardOfContract: 'File Under approval',
    agreement: 'Draft'
  },

  // ME-444 - Cardio, Physio, General, ENT (35-38)
  ...[
    { id: 't-35', slNo: 35, dept: 'Cardiology', eq: 'TPI Machine' },
    { id: 't-36', slNo: 36, dept: 'Physiotherapy', eq: 'Ultrasound Therapy' },
    { id: 't-37', slNo: 37, dept: 'General', eq: 'Sphygmoanometer' },
    { id: 't-38', slNo: 38, dept: 'ENT', eq: 'Otoscope' }
  ].map(item => ({
    id: item.id,
    slNo: item.slNo,
    department: item.dept,
    equipmentName: item.eq,
    tenderNo: 'ME-444',
    openedDate: '19.11.2025',
    endDate: '18.05.2026',
    statusText: 'Post-TEC meeting held on 17.02.2025. minutes under signing. Re-tender recommended (single bid condition).',
    manager: 'Girish',
    preBidMeeting: 'Completed',
    tscMeeting: 'Completed',
    technicalOpening: 'Opened',
    bidderName: 'Single Bidder',
    noOfBidders: 1,
    tecMeeting: 'Completed (17.02.2025)',
    postTecMeeting: 'Minutes under signing',
    tec2Meeting: 'N/A',
    demoMeeting: 'N/A',
    postDemoMeeting: 'N/A',
    financialOpening: 'Cancelled',
    priceJustificationMeeting: 'N/A',
    awardOfContract: 'Re-tender recommended (Single bid)',
    agreement: 'N/A'
  })),

  // ME-449 - Ortho (39-45)
  ...[
    { id: 't-39', slNo: 39, eq: 'Fluid Management system' },
    { id: 't-40', slNo: 40, eq: 'Surgical Power Tools: Electric Drills, Saws & Reamer Attachement.' },
    { id: 't-41', slNo: 41, eq: 'Arthroscopic Instruments: Meniscal Punches, Graspers, Scissors, Shavers, Probes.' },
    { id: 't-42', slNo: 42, eq: 'Arthroscopy Pump' },
    { id: 't-43', slNo: 43, eq: 'ACL Instrumentation Set' },
    { id: 't-44', slNo: 44, eq: 'Arthroscopic Leg Holder & Traction System' },
    { id: 't-45', slNo: 45, eq: 'External Fixator (For District Hospital/SDH/CHC/PHC)' }
  ].map(item => ({
    id: item.id,
    slNo: item.slNo,
    department: 'Ortho',
    equipmentName: item.eq,
    tenderNo: 'ME-449',
    openedDate: '28.11.2025',
    statusText: 'TEC meeting schedule on 08.05.2026. File under approval.',
    manager: 'Girish',
    preBidMeeting: 'Completed',
    tscMeeting: 'Completed',
    technicalOpening: 'Opened',
    bidderName: 'Awaiting Evaluation',
    noOfBidders: 3,
    tecMeeting: 'Scheduled (08.05.2026)',
    postTecMeeting: 'Pending',
    tec2Meeting: 'N/A',
    demoMeeting: 'Pending',
    postDemoMeeting: 'Pending',
    financialOpening: 'Pending',
    priceJustificationMeeting: 'Pending',
    awardOfContract: 'File under approval',
    agreement: 'Draft'
  })),

  // ME-452 - ENT, FMT, Physio, Cardio (46-49)
  ...[
    { id: 't-46', slNo: 46, dept: 'ENT', eq: 'ENT Examination Chair' },
    { id: 't-47', slNo: 47, dept: 'FMT', eq: 'Mortuary Table' },
    { id: 't-48', slNo: 48, dept: 'Physiotherapy', eq: 'Basic Ergo Meter' },
    { id: 't-49', slNo: 49, dept: 'Cardiology', eq: 'TMT Machine' }
  ].map(item => ({
    id: item.id,
    slNo: item.slNo,
    department: item.dept,
    equipmentName: item.eq,
    tenderNo: 'ME-452',
    openedDate: '05.12.2025',
    statusText: 'TEC meeting schedule on 08.05.2026. TEC meeting schedule on 15.05.2026. File under Approval.',
    manager: 'Girish',
    preBidMeeting: 'Completed',
    tscMeeting: 'Completed',
    technicalOpening: 'Opened',
    bidderName: 'BMSICL Nominated Board',
    noOfBidders: 3,
    tecMeeting: 'Scheduled (15.05.2026)',
    postTecMeeting: 'Review Pending',
    tec2Meeting: 'Scheduled',
    demoMeeting: 'Pending',
    postDemoMeeting: 'Pending',
    financialOpening: 'Pending',
    priceJustificationMeeting: 'Pending',
    awardOfContract: 'File under Approval',
    agreement: 'Draft'
  })),

  // ME-454 - Radiology (50-51)
  {
    id: 't-50',
    slNo: 50,
    department: 'Radiology',
    equipmentName: 'MRI Machine',
    tenderNo: 'ME-454',
    statusText: 'TEC meeting held on 21.04.2026. No firm qualified in technical evaluation; hence, re-tendering is recommended by the Technical Evaluation Committee.',
    manager: 'Girish',
    preBidMeeting: 'Completed',
    tscMeeting: 'Completed',
    technicalOpening: 'Opened',
    bidderName: 'Participants Disqualified',
    noOfBidders: 2,
    tecMeeting: 'Completed (21.04.2026)',
    postTecMeeting: 'All Disqualified',
    tec2Meeting: 'N/A',
    demoMeeting: 'N/A',
    postDemoMeeting: 'N/A',
    financialOpening: 'Cancelled',
    priceJustificationMeeting: 'N/A',
    awardOfContract: 'Re-tendering recommended',
    agreement: 'N/A'
  },
  {
    id: 't-51',
    slNo: 51,
    department: 'Radiology',
    equipmentName: 'CT Machine',
    tenderNo: 'ME-454',
    statusText: 'TEC meeting held on 21.04.2026. No firm qualified in technical evaluation; hence, re-tendering is recommended by the Technical Evaluation Committee.',
    manager: 'Girish',
    preBidMeeting: 'Completed',
    tscMeeting: 'Completed',
    technicalOpening: 'Opened',
    bidderName: 'Participants Disqualified',
    noOfBidders: 2,
    tecMeeting: 'Completed (21.04.2026)',
    postTecMeeting: 'All Disqualified',
    tec2Meeting: 'N/A',
    demoMeeting: 'N/A',
    postDemoMeeting: 'N/A',
    financialOpening: 'Cancelled',
    priceJustificationMeeting: 'N/A',
    awardOfContract: 'Re-tendering recommended',
    agreement: 'N/A'
  },

  // ME-436 - Laser Therapy Group (52-56)
  ...[
    { id: 't-52', slNo: 52, eq: 'Laser Therapy Unit' },
    { id: 't-53', slNo: 53, eq: 'Knee Continuous Passive Motion Unit' },
    { id: 't-54', slNo: 54, eq: 'Cryotherapy Unit' },
    { id: 't-55', slNo: 55, eq: 'Stethoscope' },
    { id: 't-56', slNo: 56, eq: 'Flow Meter' }
  ].map(item => ({
    id: item.id,
    slNo: item.slNo,
    department: 'General Physical Medicine',
    equipmentName: item.eq,
    tenderNo: 'ME-436',
    openedDate: '11.11.2025',
    statusText: 'Technical Opening held on 11.11.2025. Recommended to retender due to single bid received.',
    manager: 'Girish',
    preBidMeeting: 'Completed',
    tscMeeting: 'Completed',
    technicalOpening: 'Opened (11.11.2025)',
    bidderName: 'Single Bidder',
    noOfBidders: 1,
    tecMeeting: 'Completed',
    postTecMeeting: 'Re-tender Proposed',
    tec2Meeting: 'N/A',
    demoMeeting: 'N/A',
    postDemoMeeting: 'N/A',
    financialOpening: 'Cancelled',
    priceJustificationMeeting: 'N/A',
    awardOfContract: 'Recommended to Retender',
    agreement: 'N/A'
  })),

  // ME-473 - OBG / Pediatrics (57-58)
  {
    id: 't-57',
    slNo: 57,
    department: 'OBG / Paediatrics',
    equipmentName: 'Foetal Doppler',
    tenderNo: 'ME-473',
    openedDate: '25.02.2026',
    statusText: 'Clarification is sought from the bidders, to be submitted within 7-days.',
    manager: 'Girish',
    preBidMeeting: 'Completed',
    tscMeeting: 'Completed',
    technicalOpening: 'Opened',
    bidderName: 'Awaiting Clarification',
    noOfBidders: 2,
    tecMeeting: 'In Evaluation',
    postTecMeeting: 'Sought Clarification',
    tec2Meeting: 'N/A',
    demoMeeting: 'Pending',
    postDemoMeeting: 'Pending',
    financialOpening: 'Pending',
    priceJustificationMeeting: 'Pending',
    awardOfContract: 'Awaiting 7-days reply',
    agreement: 'Draft'
  },
  {
    id: 't-58',
    slNo: 58,
    department: 'OBG / Paediatrics',
    equipmentName: 'Phototherapy',
    tenderNo: 'ME-473',
    openedDate: '25.02.2026',
    statusText: 'Clarification is sought from the bidders, to be submitted within 7-days.',
    manager: 'Girish',
    preBidMeeting: 'Completed',
    tscMeeting: 'Completed',
    technicalOpening: 'Opened',
    bidderName: 'Awaiting Clarification',
    noOfBidders: 2,
    tecMeeting: 'In Evaluation',
    postTecMeeting: 'Sought Clarification',
    tec2Meeting: 'N/A',
    demoMeeting: 'Pending',
    postDemoMeeting: 'Pending',
    financialOpening: 'Pending',
    priceJustificationMeeting: 'Pending',
    awardOfContract: 'Awaiting 7-days reply',
    agreement: 'Draft'
  },

  // ME-478 - Physiotherapy Group (59-65)
  ...[
    { id: 't-59', slNo: 59, eq: 'Exercise Bed/Couch Wooden' },
    { id: 't-60', slNo: 60, eq: 'Quadriceps Chair' },
    { id: 't-61', slNo: 61, eq: 'Pulse Shortwave' },
    { id: 't-62', slNo: 62, eq: 'Traction Unit (Cervical & Lumber ) with Bed' },
    { id: 't-63', slNo: 63, eq: 'Laser Therapy Unit' },
    { id: 't-64', slNo: 64, eq: 'Cryotherapy Compression Unit' },
    { id: 't-65', slNo: 65, eq: 'Knee Continuous Passive Motion Unit' }
  ].map(item => ({
    id: item.id,
    slNo: item.slNo,
    department: 'Physiotherapy',
    equipmentName: item.eq,
    tenderNo: 'ME-478',
    statusText: 'Pre-Bid meeting held on 06.04.2026. TSC meeting held on 24.04.2026. Technical Opening schedule on 20.05.2026 File under Approval.',
    manager: 'Girish',
    preBidMeeting: 'Completed (06.04.2026)',
    tscMeeting: 'Completed (24.04.2026)',
    technicalOpening: 'Scheduled (20.05.2026)',
    bidderName: 'Awaiting Opening',
    noOfBidders: 0,
    tecMeeting: 'Pending',
    postTecMeeting: 'Pending',
    tec2Meeting: 'Pending',
    demoMeeting: 'Pending',
    postDemoMeeting: 'Pending',
    financialOpening: 'Pending',
    priceJustificationMeeting: 'Pending',
    awardOfContract: 'File under Approval',
    agreement: 'Draft'
  })),

  // ME-474 - Flow Meter, Cardi, Medicine (66-72)
  ...[
    { id: 't-66', slNo: 66, dept: 'General Medicine', eq: 'Flow Meter' },
    { id: 't-67', slNo: 67, dept: 'General Medicine', eq: 'Stethoscope' },
    { id: 't-68', slNo: 68, dept: 'General Medicine', eq: 'Sphygmomanometer' },
    { id: 't-69', slNo: 69, dept: 'Cardiology', eq: 'TPI Machine' },
    { id: 't-70', slNo: 70, dept: 'Cardiology', eq: 'TMT Machine' },
    { id: 't-71', slNo: 71, dept: 'General Medicine', eq: 'Wheel Chair' },
    { id: 't-72', slNo: 72, dept: 'General Medicine', eq: 'Medicine Tray' }
  ].map(item => ({
    id: item.id,
    slNo: item.slNo,
    department: item.dept,
    equipmentName: item.eq,
    tenderNo: 'ME-474',
    statusText: 'TEC meeting held on 29.04.2026. Clarification is sought from the bidders, to be submitted within 7-days.',
    manager: 'Girish',
    preBidMeeting: 'Completed',
    tscMeeting: 'Completed',
    technicalOpening: 'Opened',
    bidderName: 'Pending Clarification Replies',
    noOfBidders: 3,
    tecMeeting: 'Completed (29.04.2026)',
    postTecMeeting: 'Clarification Issued',
    tec2Meeting: 'N/A',
    demoMeeting: 'Pending',
    postDemoMeeting: 'Pending',
    financialOpening: 'Pending',
    priceJustificationMeeting: 'Pending',
    awardOfContract: 'Clarification Pending',
    agreement: 'Draft'
  })),

  // ME-475 - Central Monitoring (73-74)
  {
    id: 't-73',
    slNo: 73,
    department: 'Critical Care Dept.',
    equipmentName: 'Central Monitoring station with Cardiac Monitor',
    tenderNo: 'ME-475',
    statusText: 'TEC meeting held on 24.04.2026. Clarification is sought from the bidders, to be submitted within 7-days.',
    manager: 'Girish',
    preBidMeeting: 'Completed',
    tscMeeting: 'Completed',
    technicalOpening: 'Opened',
    bidderName: 'Awaiting Clarification Answers',
    noOfBidders: 3,
    tecMeeting: 'Completed (24.04.2026)',
    postTecMeeting: 'Clarification Sought',
    tec2Meeting: 'N/A',
    demoMeeting: 'Pending',
    postDemoMeeting: 'Pending',
    financialOpening: 'Pending',
    priceJustificationMeeting: 'Pending',
    awardOfContract: 'Clarification Pending',
    agreement: 'Draft'
  },
  {
    id: 't-74',
    slNo: 74,
    department: 'Critical Care Dept.',
    equipmentName: 'Central Monitoring station with Multi-Para Monitor',
    tenderNo: 'ME-475',
    statusText: 'TEC meeting held on 24.04.2026. Clarification is sought from the bidders, to be submitted within 7-days.',
    manager: 'Girish',
    preBidMeeting: 'Completed',
    tscMeeting: 'Completed',
    technicalOpening: 'Opened',
    bidderName: 'Awaiting Clarification Answers',
    noOfBidders: 3,
    tecMeeting: 'Completed (24.04.2026)',
    postTecMeeting: 'Clarification Sought',
    tec2Meeting: 'N/A',
    demoMeeting: 'Pending',
    postDemoMeeting: 'Pending',
    financialOpening: 'Pending',
    priceJustificationMeeting: 'Pending',
    awardOfContract: 'Clarification Pending',
    agreement: 'Draft'
  },

  // ME-477 - Large Physics/Spirometer Group (75-86)
  ...[
    { id: 't-75', slNo: 75, eq: 'Electrical E8 student kymograph' },
    { id: 't-76', slNo: 76, eq: 'Perimeter Pristely Smith model' },
    { id: 't-77', slNo: 77, eq: 'Mosso’s Ergograph' },
    { id: 't-78', slNo: 78, eq: 'Perimeter Lister type' },
    { id: 't-79', slNo: 79, eq: 'Digital Perimeter' },
    { id: 't-80', slNo: 80, eq: 'Bicycle Ergometer' },
    { id: 't-81', slNo: 81, eq: 'Pentahead microscope' },
    { id: 't-82', slNo: 82, eq: 'Wright Peak flowmeter' },
    { id: 't-83', slNo: 83, eq: 'Handgrip dynamometer' },
    { id: 't-84', slNo: 84, eq: 'Demonstration stethoscope' },
    { id: 't-85', slNo: 85, eq: 'Harvard step (Wooden Box) 20” Males, 16” Females' },
    { id: 't-86', slNo: 86, eq: 'Spirometer Digital' }
  ].map(item => ({
    id: item.id,
    slNo: item.slNo,
    department: 'Physiology Equipment Section',
    equipmentName: item.eq,
    tenderNo: 'ME-477',
    statusText: 'Pre-Bid meeting held on 20.04.2026. Technical opening schedule on 20.05.2026',
    manager: 'Girish',
    preBidMeeting: 'Completed (20.04.2026)',
    tscMeeting: 'Completed',
    technicalOpening: 'Scheduled (20.05.2026)',
    bidderName: 'Awaiting Bids',
    noOfBidders: 0,
    tecMeeting: 'Pending',
    postTecMeeting: 'Pending',
    tec2Meeting: 'Pending',
    demoMeeting: 'Pending',
    postDemoMeeting: 'Pending',
    financialOpening: 'Pending',
    priceJustificationMeeting: 'Pending',
    awardOfContract: 'Awaiting Opening',
    agreement: 'Draft'
  })),

  // ME-476 - Microwave Sterilization (87)
  {
    id: 't-87',
    slNo: 87,
    department: 'Waste Management',
    equipmentName: 'Microwave based Medial waste sterilization system',
    tenderNo: 'ME-476',
    statusText: 'The file has been forwarded for publication of the tender and approval is awaited.',
    manager: 'Girish',
    preBidMeeting: 'Pending Publication',
    tscMeeting: 'Pending Publication',
    technicalOpening: 'Awaiting Publication',
    bidderName: 'N/A',
    noOfBidders: 0,
    tecMeeting: 'Pending',
    postTecMeeting: 'Pending',
    tec2Meeting: 'Pending',
    demoMeeting: 'Pending',
    postDemoMeeting: 'Pending',
    financialOpening: 'Pending',
    priceJustificationMeeting: 'Pending',
    awardOfContract: 'Awaiting Publication Approval',
    agreement: 'Draft'
  },

  // ME-487 - MRI Betttiah Core (88)
  {
    id: 't-88',
    slNo: 88,
    department: 'Radiology Dept (GMCH)',
    equipmentName: 'MRI MACHINE (GMCH, BETTIAH)',
    tenderNo: 'ME-487',
    statusText: 'TSC meeting held on 10.04.2026. Technical Opening schedule on 20.05.2026. File under Approval.',
    manager: 'Girish',
    preBidMeeting: 'Completed',
    tscMeeting: 'Completed (10.04.2026)',
    technicalOpening: 'Scheduled (20.05.2026)',
    bidderName: 'Awaiting Submissions',
    noOfBidders: 0,
    tecMeeting: 'Pending',
    postTecMeeting: 'Pending',
    tec2Meeting: 'Pending',
    demoMeeting: 'Pending',
    postDemoMeeting: 'Pending',
    financialOpening: 'Pending',
    priceJustificationMeeting: 'Pending',
    awardOfContract: 'File under Approval',
    agreement: 'Draft'
  },

  // ME-489 - Cardiology (89-90)
  {
    id: 't-89',
    slNo: 89,
    department: 'Cardiology',
    equipmentName: 'High End Echocardiography-10',
    tenderNo: 'ME-489',
    openedDate: '20.05.2026',
    statusText: 'Pre-Bid meeting held on 06.05.2026. TSC meeting schedule on 15.05.2026. File movement for TSC meeting. Technical Opening schedule on 27.05.2026.',
    manager: 'Girish',
    preBidMeeting: 'Completed (06.05.2026)',
    tscMeeting: 'Scheduled (15.05.2026)',
    technicalOpening: 'Scheduled (27.05.2026)',
    bidderName: 'Awaiting Bids',
    noOfBidders: 0,
    tecMeeting: 'Pending',
    postTecMeeting: 'Pending',
    tec2Meeting: 'Pending',
    demoMeeting: 'Pending',
    postDemoMeeting: 'Pending',
    financialOpening: 'Pending',
    priceJustificationMeeting: 'Pending',
    awardOfContract: 'TSC file movement',
    agreement: 'Draft'
  },
  {
    id: 't-90',
    slNo: 90,
    department: 'Cardiology',
    equipmentName: 'Echocardiogram (ECHO) Machine-36',
    tenderNo: 'ME-489',
    openedDate: '20.05.2026',
    statusText: 'Pre-Bid meeting held on 06.05.2026. TSC meeting schedule on 15.05.2026. File movement for TSC meeting. Technical Opening schedule on 27.05.2026.',
    manager: 'Girish',
    preBidMeeting: 'Completed (06.05.2026)',
    tscMeeting: 'Scheduled (15.05.2026)',
    technicalOpening: 'Scheduled (27.05.2026)',
    bidderName: 'Awaiting Bids',
    noOfBidders: 0,
    tecMeeting: 'Pending',
    postTecMeeting: 'Pending',
    tec2Meeting: 'Pending',
    demoMeeting: 'Pending',
    postDemoMeeting: 'Pending',
    financialOpening: 'Pending',
    priceJustificationMeeting: 'Pending',
    awardOfContract: 'TSC file movement',
    agreement: 'Draft'
  },

  // ME-495 - Radiology Def/CT (91-92)
  {
    id: 't-91',
    slNo: 91,
    department: 'Radiology',
    equipmentName: 'MRI Machine',
    tenderNo: 'ME-495',
    statusText: 'Pre-Bid meeting held on 05.05.2026. TSC meeting schedule on 14.05.2026. File under approval.',
    manager: 'Girish',
    preBidMeeting: 'Completed (05.05.2026)',
    tscMeeting: 'Scheduled (14.05.2026)',
    technicalOpening: 'Scheduled',
    bidderName: 'Awaiting Openings',
    noOfBidders: 0,
    tecMeeting: 'Pending',
    postTecMeeting: 'Pending',
    tec2Meeting: 'Pending',
    demoMeeting: 'Pending',
    postDemoMeeting: 'Pending',
    financialOpening: 'Pending',
    priceJustificationMeeting: 'Pending',
    awardOfContract: 'File under approval',
    agreement: 'Draft'
  },
  {
    id: 't-92',
    slNo: 92,
    department: 'Radiology',
    equipmentName: 'CT Machine',
    tenderNo: 'ME-495',
    statusText: 'Pre-Bid meeting held on 05.05.2026. TSC meeting schedule on 14.05.2026. File under approval.',
    manager: 'Girish',
    preBidMeeting: 'Completed (05.05.2026)',
    tscMeeting: 'Scheduled (14.05.2026)',
    technicalOpening: 'Scheduled',
    bidderName: 'Awaiting Openings',
    noOfBidders: 0,
    tecMeeting: 'Pending',
    postTecMeeting: 'Pending',
    tec2Meeting: 'Pending',
    demoMeeting: 'Pending',
    postDemoMeeting: 'Pending',
    financialOpening: 'Pending',
    priceJustificationMeeting: 'Pending',
    awardOfContract: 'File under approval',
    agreement: 'Draft'
  },

  // ME-494 - Bubble CPAP (93)
  {
    id: 't-93',
    slNo: 93,
    department: 'Neonatal Critical Care',
    equipmentName: 'Cpap Machine (bubble Cpap)',
    tenderNo: 'ME-494',
    statusText: 'TSC meeting held on 06th May 2026. Letter sent to concern officer.',
    manager: 'Girish',
    preBidMeeting: 'Completed',
    tscMeeting: 'Completed (06.05.2026)',
    technicalOpening: 'Awaiting officer response',
    bidderName: 'N/A',
    noOfBidders: 0,
    tecMeeting: 'Pending',
    postTecMeeting: 'Pending',
    tec2Meeting: 'Pending',
    demoMeeting: 'Pending',
    postDemoMeeting: 'Pending',
    financialOpening: 'Pending',
    priceJustificationMeeting: 'Pending',
    awardOfContract: 'Letter sent to concern officer',
    agreement: 'Draft'
  },

  // ME-497 - General ENT/Ultrasound (94-98)
  ...[
    { id: 't-94', slNo: 94, eq: 'ENT Examination Chair' },
    { id: 't-95', slNo: 95, eq: 'Ultrasound Therapy' },
    { id: 't-96', slNo: 96, eq: 'Otoscope' },
    { id: 't-97', slNo: 97, eq: 'Sphygmomanometer' },
    { id: 't-98', slNo: 98, eq: 'Flow Meter' }
  ].map(item => ({
    id: item.id,
    slNo: item.slNo,
    department: 'General Equipment Registry',
    equipmentName: item.eq,
    tenderNo: 'ME-497',
    openedDate: '01.06.2026',
    statusText: 'The file has been forwarded for publication of the tender and approval is awaited.',
    manager: 'Girish',
    preBidMeeting: 'Pending Publication',
    tscMeeting: 'Pending Publication',
    technicalOpening: 'Scheduled (01.06.2026)',
    bidderName: 'N/A',
    noOfBidders: 0,
    tecMeeting: 'Pending',
    postTecMeeting: 'Pending',
    tec2Meeting: 'Pending',
    demoMeeting: 'Pending',
    postDemoMeeting: 'Pending',
    financialOpening: 'Pending',
    priceJustificationMeeting: 'Pending',
    awardOfContract: 'File forwarded for publication',
    agreement: 'Draft'
  }))
];
